### ISSUE TITLE
Code gone?

### ISSUE THREAD

**Issue by Rich700000000000** [dmahony/Lora-Chat-Device#9]
What happened to all the code?

**Comment by dmahony** [comment]
There was hardly any difference to the pySX127x repo and I couldn't
continue working on that because my python skills weren't quite good enough
and wasn't getting any help. This new version works much better and has
more features. There is no code here because I'm still figuring how it will
all work, I'm hoping to upload a Raspberry Pi image somewhere soon.

**Comment by Rich700000000000** [comment]
Cool. 

What did you need help with, specifically? I'm great with python, I could take a look at it. I actually really liked your project: It reminded me of ProxyHam.

What hardware do I need, besides a RasPi?

**Comment by dmahony** [comment]
The new version is much better, there is more features and it uses the ax25
protocol which has been around for years and works great. If you check the
readme on the project page you will find all the info you need. I've also
set up a wiki page with installation instructions:
https://github.com/dmahony/Lora-Chat-Device/wiki/Installation-Instructions
